In [17]:
import numpy as np
import MeCab

tagger = MeCab.Tagger("-d /var/lib/mecab/dic/mecab-ipadic-neologd")
word_dic = {'__id': 0}
files = []
dt_dic = {}

def tokenize(text):
    n = tagger.parse(text)
    result = []
    for w in n.split('\n'):
        if w == "EOS" or w == '': continue
        t = w.split('\t')[1]
        t_s = t.split(",")
        if not (t_s[0] in ['名詞', '動詞', '形容詞']): continue
        if t_s[0] in '名詞' and t_s[1] in '数': continue
        result.append(t_s[6])
    return result

def words_to(words, add_bool=True):
    result = []
    for wo in words:
        if wo in word_dic:
            result.append(word_dic[wo])
            continue
        elif add_bool:
            id = word_dic[wo] = word_dic['__id']
            word_dic['__id'] += 1
            result.append(id)
    return result
    
     
def add_text(text):
    id_w = words_to(tokenize(text))
    files.append(id_w)
    
def calc_tf():
    global dt_dic
    
    d_t = []
    result =[]
    for f in files:
        data = np.zeros(word_dic['__id'])
        for f_n in f:
            if not f_n in dt_dic:
                dt_dic[f_n] = 0
            dt_dic[f_n] += 1
            data[f_n] += 1
        data = data / len(f)
        d_t.append(data)
    
    for i,d in enumerate(d_t):
        for id, v in enumerate(d):
            idf = np.log(len(files) / dt_dic[id])+1
            d[id] = min([v*idf, 1.0])
        result.append()

        
        
       

if __name__ == '__main__':
    add_text('雨')
    add_text('今日は、雨が降った。')
    add_text('今日は暑い日だったけど雨が降った。')
    add_text('今日も雨だ。でも日曜だ。')
    print(calc_tf())

[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[0.33333333 0.33333333 0.33333333 0.         0.         0.        ]
[0.33333333 0.42922736 0.33333333 0.         0.         0.        ]
[0.33333333 0.42922736 0.56438239 0.         0.         0.        ]
[0.33333333 0.42922736 0.56438239 0.         0.         0.        ]
[0.33333333 0.42922736 0.56438239 0.         0.         0.        ]
[0.33333333 0.42922736 0.56438239 0.         0.         0.        ]
[0.2 0.2 0.2 0.2 0.2 0. ]
[0.2        0.25753641 0.2        0.2        0.2        0.        ]
[0.2        0.25753641 0.33862944 0.2        0.2        0.        ]
[0.2        0.25753641 0.33862944 0.47725887 0.2        0.        ]
[0.2        0.25753641 0.33862944 0.47725887 0.47725887 0.        ]
[0.2        0.25753641 0.33862944 0.47725887 0.47725887 0.        ]
[0.33333333 0.33333333 0.         0.         0.         0.33333333]
[0.33333333 0.42922736 0.         0.  